### ISSUE TITLE
bug when searching for team

### ISSUE THREAD

**Issue by xuatz** [prattl/teamfinder#11]
url: https://dotateamfinder.com/teams
region filter: SE Asia
position: 1, 4

After keying these values, the page is stuck at loading. Screenshot below.

![image](https://cloud.githubusercontent.com/assets/9292261/24855952/b52ffb76-1e15-11e7-80a0-3aaf183e261b.png)

**Comment by prattl** [comment]
Thanks! Just fixed this in 3df2bccc27618d26930d139df588b765de4d33a8.
